### ISSUE TITLE
OneClickInstaller doesn't store customized path

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#491]
When installing, the user is able to choose a different install path than Stereum's default `/opt/stereum`. This path isn't saved to the config `/etc/stereum/stereum.yaml`:
```
# cat /etc/stereum/stereum.yaml 
# Stereum system settings
stereum_settings:
  settings:
    controls_install_path: /opt/stereum
    os_user: stereum
    updates:
      lane: stable
      unattended:
        install: False
```
