### ISSUE TITLE
Blox SSV config file formatting incorrect

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#584]
How it looks like now:
```
eth2:
  Network: prater
  BeaconNodeAddr: http://stereum-F0ii7yIB-9IJQ-bG0N-mbv1-g5MIOdNCcgQw:5052
eth1:
  ETH1Addr: http://stereum-n5eoQbtY-vBd7-ERR5-11sr-iY5KDGXQmWi0:8545
  RegistryContractAddr: ""
OperatorPrivateKey: LS0tLS1C...RVktLS0tLQo=
global:
  LogLevel: info
MetricsAPIPort: 15000
```

How it should look like:
```
eth2:
  Network: "prater"
  BeaconNodeAddr: "http://stereum-F0ii7yIB-9IJQ-bG0N-mbv1-g5MIOdNCcgQw:5052"
eth1:
  ETH1Addr: "ws://stereum-n5eoQbtY-vBd7-ERR5-11sr-iY5KDGXQmWi0:8546"
  RegistryContractAddr: "0x687fb596F3892904F879118e2113e1EEe8746C2E"
OperatorPrivateKey: "LS0tLS1CRUdJ...LRVktLS0tLQo="
global:
  LogLevel: info
MetricsAPIPort: 15000
```

Changes:

- [x] use double quotes for all strings
- [x] RegistryContractAddr needs to be filled
- [x] #580
