### ISSUE TITLE
Blox SSV config contains wrong el port

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#617]
Right now with https://github.com/stereum-dev/ethereum-node/releases/tag/v2.0.0-stack-rc4 the setup uses port `8551` for websocket connection to el (used geth & teku), which is the RPC port. It should be the websocket port `8546` (for geth).

fixed config.yaml of Blox SSV:
```
eth2:
  Network: "prater"
  BeaconNodeAddr: "http://stereum-fWEfcQNS-zuIZ-pmDF-I6eT-zNvNczjknHW8:5051"
eth1:
  ETH1Addr: "ws://stereum-c33z1Ld8-pEW5-gg1f-c6l7-xIcbbg7EnY5O:8546"
  RegistryContractAddr: "0x687fb596F3892904F879118e2113e1EEe8746C2E"
OperatorPrivateKey: "LS0tLS1CRUdJTiBS...LS0tLQo="
global:
  LogLevel: info
MetricsAPIPort: 15000
```

geth service yaml:
```
service: GethService
id: c33z1Ld8-pEW5-gg1f-c6l7-xIcbbg7EnY5O
configVersion: 1
command:
  - --goerli
  - --datadir=/opt/data/geth
  - --http
  - --http.port=8545
  - --http.addr=0.0.0.0
  - --http.vhosts=*
  - --http.api="engine,eth,web3,net,debug"
  - --http.corsdomain=*
  - --ws
  - --ws.port=8546
  - --ws.addr=0.0.0.0
  - --ws.api="debug,eth,net,web3"
  - --ws.origins=*
  - --authrpc.addr=0.0.0.0
  - --authrpc.vhosts=*
  - --authrpc.jwtsecret=/engine.jwt
  - --metrics
  - --metrics.expensive
  - --metrics.port=6060
  - --metrics.addr=0.0.0.0
entrypoint:
  - geth
env:
  STEREUM_DUMMY: foobar
image: ethereum/client-go:v1.10.21
ports:
  - 0.0.0.0:30303:30303/tcp
  - 0.0.0.0:30303:30303/udp
  - 127.0.0.1:8551:8551/tcp
restart_policy: null
volumes:
  - /opt/stereum/geth-c33z1Ld8-pEW5-gg1f-c6l7-xIcbbg7EnY5O/data:/opt/data/geth
  - /opt/stereum/geth-c33z1Ld8-pEW5-gg1f-c6l7-xIcbbg7EnY5O/engine.jwt:/engine.jwt
user: root
autoupdate: true
network: goerli
dependencies:
  executionClients: []
  consensusClients: []
  prometheusNodeExporterClients: []
```
